export const texts = [
  { text: "The rapid advancements in artificial intelligence are reshaping the future of technology. Machine learning algorithms are becoming more sophisticated, enabling computers to perform tasks once thought impossible. As AI continues to evolve, its impact on industries such as healthcare, finance, and transportation grows more profound." },
  { text: "The universe is a vast and mysterious place, filled with countless galaxies and celestial bodies. Astronomers use powerful telescopes to explore the cosmos and uncover its secrets. The study of stars and planets not only satisfies our curiosity but also helps us understand our place in the universe." },
  { text: "A well-prepared meal can be a source of immense pleasure and satisfaction. The art of cooking involves selecting the finest ingredients and using various techniques to enhance their flavors. From the sizzle of vegetables in a hot pan to the aroma of freshly baked bread, cooking is a sensory experience that brings people together." },
  { text: "In the world of science, breakthroughs are constantly being made that challenge our understanding of the natural world. Researchers conduct experiments and analyze data to uncover new phenomena. Their discoveries lead to innovations that improve our quality of life and solve pressing global issues." },
  { text: "Love is a powerful emotion that can bring immense joy and profound sorrow. It has inspired countless works of art, literature, and music throughout history. Whether it's the love between family members, friends, or romantic partners, this feeling is a fundamental part of the human experience." },
  { text: "Movies are a form of storytelling that combines visual art with narrative. Directors use camera angles, lighting, and sound to create immersive experiences for audiences. From action-packed blockbusters to thought-provoking dramas, films have the power to entertain, educate, and inspire." },
  { text: "The advent of renewable energy sources is transforming the way we generate and consume power. Solar panels, wind turbines, and hydroelectric dams harness natural forces to produce electricity. These technologies reduce our reliance on fossil fuels and help combat climate change." },
  { text: "Space exploration has always been a frontier of human ambition and curiosity. The International Space Station orbits Earth, serving as a hub for scientific research. Missions to Mars and beyond aim to uncover the potential for life on other planets and expand our understanding of the universe." },
  { text: "The culinary world is vast and diverse, with each culture offering its unique flavors and dishes. From the spicy curries of India to the delicate sushi of Japan, food is a reflection of a region's history and traditions. Exploring different cuisines broadens our palate and appreciation for global diversity." },
  { text: "Advancements in medical technology are revolutionizing healthcare. Innovations such as robotic surgery, telemedicine, and personalized medicine are improving patient outcomes. These developments not only enhance the quality of care but also make healthcare more accessible and efficient." },
  { text: "The mysteries of the ocean depths continue to captivate scientists and explorers. Marine biologists study the diverse ecosystems that thrive beneath the waves. Discoveries of new species and underwater phenomena contribute to our knowledge of Earth's final frontier." },
  { text: "Music is a universal language that transcends cultural and linguistic barriers. It has the power to evoke emotions, tell stories, and bring people together. From classical compositions to modern pop hits, music plays a significant role in our lives and society." },
  { text: "The digital age has transformed the way we communicate and access information. Social media platforms connect people across the globe, allowing for instant sharing of ideas and experiences. The internet has become an essential tool for education, business, and entertainment." },
  { text: "The study of genetics has opened new avenues for understanding human biology. By analyzing DNA, scientists can identify genetic predispositions to diseases and develop targeted treatments. This field holds promise for advancements in personalized medicine and healthcare." },
  { text: "Art and creativity are fundamental aspects of human expression. Whether through painting, sculpture, or digital media, artists convey their thoughts and emotions. Art galleries and museums showcase these works, offering insight into different cultures and historical periods." },
  { text: "Environmental conservation is crucial for preserving the planet's biodiversity. Efforts to protect endangered species and restore natural habitats are gaining momentum. Sustainable practices in agriculture, industry, and everyday life help ensure a healthy environment for future generations." },
  { text: "The field of robotics is advancing rapidly, with machines becoming more capable and versatile. Robots are used in manufacturing, healthcare, and even space exploration. Their ability to perform repetitive tasks and operate in hazardous environments makes them invaluable tools." },
  { text: "Astronomy has always been a field that inspires wonder and curiosity. The study of celestial bodies and cosmic phenomena helps us understand the universe's origins and evolution. Telescopes and space probes provide glimpses into distant galaxies and the potential for extraterrestrial life." },
  { text: "The culinary arts encompass a wide range of techniques and traditions. Chefs experiment with flavors and presentation to create memorable dining experiences. From gourmet restaurants to street food stalls, the world of food is rich with diversity and innovation." },
  { text: "Healthcare advancements continue to improve patient care and outcomes. New treatments and technologies are developed through rigorous scientific research. Preventive medicine and public health initiatives play a crucial role in maintaining population health." },
  { text: "The exploration of space has led to numerous technological innovations. Satellites provide critical data for weather forecasting, navigation, and communication. As we venture further into the cosmos, the potential for new discoveries and advancements grows exponentially." },
  { text: "The world of literature offers an endless array of stories and knowledge. Books transport readers to different times and places, fostering imagination and empathy. From classic novels to contemporary works, literature enriches our lives and broadens our perspectives." },
  { text: "Technological advancements in renewable energy are reshaping the power industry. Solar, wind, and hydroelectric power offer sustainable alternatives to fossil fuels. These energy sources help reduce carbon emissions and combat climate change." },
  { text: "The ocean remains one of the least explored areas on Earth. Marine biologists and oceanographers study the complex ecosystems that exist beneath the surface. Discoveries of new species and geological formations continue to expand our understanding of the marine world." },
  { text: "Music has the power to evoke a wide range of emotions and connect people. From symphonies to rock concerts, musical performances create shared experiences. Musicians and composers draw on diverse influences to craft songs that resonate with audiences worldwide." },
  { text: "The rise of digital technology has revolutionized many aspects of our lives. Smartphones, tablets, and computers provide instant access to information and communication. The internet connects people globally, enabling the exchange of ideas and cultures." },
  { text: "Genetic research is uncovering the secrets of human biology and disease. Scientists study DNA to identify genetic markers associated with various health conditions. Advances in genetics hold promise for personalized medicine and targeted therapies." },
  { text: "Artistic expression takes many forms, from traditional painting to digital media. Artists use their creativity to communicate ideas and emotions. Art exhibitions and installations provide opportunities for the public to engage with and appreciate these works." },
  { text: "Conservation efforts are essential for protecting the environment and wildlife. Organizations and activists work to preserve natural habitats and combat pollution. Sustainable practices in agriculture, industry, and daily life contribute to a healthier planet." },
  { text: "Robotics technology is advancing at a rapid pace, with applications across various fields. Robots assist in manufacturing, healthcare, and even household tasks. Their ability to perform repetitive or dangerous jobs makes them valuable assets in many industries." },
  { text: "Astronomy continues to reveal the wonders of the universe. Telescopes and space missions provide insights into distant galaxies and celestial phenomena. The search for extraterrestrial life and understanding cosmic events remain central to this field of study." },
  { text: "The culinary arts celebrate the diversity of food and cooking techniques. Chefs and home cooks alike experiment with flavors and ingredients. Culinary traditions reflect cultural heritage and offer a glimpse into different ways of life." },
  { text: "Medical science is continually evolving, leading to improved treatments and care. Researchers work tirelessly to develop new medications and therapies. Preventive health measures and public health initiatives are vital for maintaining population health." },
  { text: "Space exploration has led to many technological advancements that benefit life on Earth. Satellites aid in communication, navigation, and environmental monitoring. The ongoing quest to explore other planets and moons drives innovation and scientific discovery." },
  { text: "Literature offers a wealth of stories and knowledge to readers. Books transport us to different worlds and times, fostering imagination and empathy. From classic literature to modern fiction, the written word enriches our lives in countless ways." },
  { text: "Renewable energy technologies are crucial for a sustainable future. Solar panels, wind turbines, and hydroelectric dams generate power without depleting resources. These clean energy sources help reduce greenhouse gas emissions and combat climate change." },
  { text: "The ocean's depths hold many secrets waiting to be discovered. Marine scientists explore underwater ecosystems and study marine life. Their research contributes to our understanding of biodiversity and the health of the planet's oceans." },
  { text: "Music is a powerful form of expression that transcends cultural boundaries. It can evoke emotions, tell stories, and bring people together. Whether listening to a symphony or a pop song, music plays a significant role in our lives." },
  { text: "Digital technology has transformed the way we live, work, and communicate. The internet connects people around the world, enabling instant sharing of information. Social media platforms, online education, and e-commerce have become integral parts of modern life." },
  { text: "Genetic research is unlocking new insights into human health and disease. By studying DNA, scientists can identify genetic markers and develop targeted treatments. This field holds promise for advancements in personalized medicine and improved patient care." },
  { text: "Artistic creativity enriches our lives and cultures. Artists use various mediums to express their ideas and emotions. Art galleries and museums showcase works that inspire, provoke thought, and reflect the diversity of human experience." },
  { text: "Environmental conservation is critical for protecting ecosystems and wildlife. Efforts to reduce pollution and preserve natural habitats are essential. Sustainable practices in everyday life contribute to a healthier planet for future generations." },
  { text: "The field of robotics continues to evolve, with machines becoming more advanced. Robots are used in industries ranging from manufacturing to healthcare. Their ability to perform complex tasks efficiently makes them invaluable tools in many sectors." },
  { text: "Astronomy explores the mysteries of the cosmos, from stars to galaxies. Telescopes and space missions provide insights into celestial phenomena. Understanding the universe helps us comprehend our place within it and the potential for life beyond Earth." },
  { text: "The culinary arts bring joy and creativity to the kitchen. Chefs experiment with ingredients and techniques to create delicious dishes. Food is a reflection of culture and tradition, offering a taste of different parts of the world." },
  { text: "Medical advancements continue to improve healthcare and patient outcomes. New treatments and technologies are developed through scientific research. Preventive health measures and public health initiatives are crucial for maintaining community health." },
  { text: "Space exploration inspires innovation and scientific discovery. Satellites orbit the Earth, providing data for communication and environmental monitoring. Missions to other planets seek to uncover the mysteries of the cosmos and the potential for extraterrestrial life." },
  { text: "Literature offers a vast array of stories and perspectives. Books transport readers to different worlds and times, fostering imagination and empathy. From classic novels to contemporary works, literature enriches our lives and broadens our understanding of humanity." },
  { text: "Renewable energy sources are essential for a sustainable future. Solar, wind, and hydroelectric power provide clean alternatives to fossil fuels. These technologies help reduce greenhouse gas emissions and mitigate the effects of climate change." },
  { text: "The ocean is home to diverse ecosystems and marine life. Scientists explore underwater habitats to understand their complexity and significance. Discoveries of new species and geological features contribute to our knowledge of the marine environment." },
  { text: "Music has the ability to evoke a wide range of emotions and connect people. From classical symphonies to modern pop songs, music is a universal language. It plays a significant role in cultural expression and personal enjoyment." },
  { text: "Digital technology has revolutionized communication and information access. The internet connects people globally, enabling the exchange of ideas and knowledge. Social media, online education, and e-commerce have become integral parts of modern society." },
  { text: "Genetic research is advancing our understanding of human biology and disease. By analyzing DNA, scientists can identify genetic markers and develop targeted therapies. This field holds promise for personalized medicine and improved healthcare outcomes." },
  { text: "Artistic expression enriches our lives and reflects cultural diversity. Artists use various mediums to convey their ideas and emotions. Art exhibitions and installations provide opportunities for public engagement and appreciation." },
  { text: "Environmental conservation is vital for protecting natural resources and biodiversity. Efforts to reduce pollution and preserve ecosystems are essential. Sustainable practices in agriculture, industry, and daily life contribute to a healthier planet." },
  { text: "The field of robotics is making significant strides in technology and application. Robots assist in tasks ranging from manufacturing to healthcare. Their precision and efficiency make them valuable assets in many industries." },
  { text: "Astronomy continues to uncover the wonders of the universe. Telescopes and space probes explore distant galaxies and cosmic phenomena. The study of celestial bodies helps us understand the origins and evolution of the cosmos." },
  { text: "The culinary arts celebrate the diversity of food and cooking traditions. Chefs and home cooks experiment with flavors and techniques to create memorable meals. Food is a reflection of cultural heritage and offers a taste of different parts of the world." },
  { text: "Advancements in medical science are improving healthcare and patient outcomes. Researchers develop new treatments and technologies through scientific research. Preventive medicine and public health initiatives play a crucial role in maintaining population health." },
  { text: "Space exploration has led to numerous technological innovations. Satellites provide data for communication, navigation, and environmental monitoring. Missions to other planets seek to uncover the mysteries of the cosmos and the potential for extraterrestrial life." },
  { text: "Literature offers a wealth of stories and knowledge to readers. Books transport us to different times and places, fostering imagination and empathy. From classic literature to contemporary works, the written word enriches our lives in countless ways." },
  { text: "Renewable energy technologies are crucial for a sustainable future. Solar panels, wind turbines, and hydroelectric dams generate power without depleting resources. These clean energy sources help reduce greenhouse gas emissions and combat climate change." },
  { text: "The ocean's depths hold many secrets waiting to be discovered. Marine scientists explore underwater ecosystems and study marine life. Their research contributes to our understanding of biodiversity and the health of the planet's oceans." },
  { text: "Music is a powerful form of expression that transcends cultural boundaries. It can evoke emotions, tell stories, and bring people together. Whether listening to a symphony or a pop song, music plays a significant role in our lives." },
  { text: "Digital technology has transformed the way we live, work, and communicate. The internet connects people around the world, enabling instant sharing of information. Social media platforms, online education, and e-commerce have become integral parts of modern life." },
  { text: "Genetic research is unlocking new insights into human health and disease. By studying DNA, scientists can identify genetic markers and develop targeted treatments. This field holds promise for advancements in personalized medicine and improved patient care." },
  { text: "Artistic creativity enriches our lives and cultures. Artists use various mediums to express their ideas and emotions. Art galleries and museums showcase works that inspire, provoke thought, and reflect the diversity of human experience." },
  { text: "Environmental conservation is critical for protecting ecosystems and wildlife. Efforts to reduce pollution and preserve natural habitats are essential. Sustainable practices in everyday life contribute to a healthier planet for future generations." },
  { text: "The field of robotics continues to evolve, with machines becoming more advanced. Robots are used in industries ranging from manufacturing to healthcare. Their ability to perform complex tasks efficiently makes them invaluable tools in many sectors." },
  { text: "Astronomy explores the mysteries of the cosmos, from stars to galaxies. Telescopes and space missions provide insights into celestial phenomena. Understanding the universe helps us comprehend our place within it and the potential for life beyond Earth." },
  { text: "The culinary arts bring joy and creativity to the kitchen. Chefs experiment with ingredients and techniques to create delicious dishes. Food is a reflection of culture and tradition, offering a taste of different parts of the world." },
  { text: "Medical advancements continue to improve healthcare and patient outcomes. New treatments and technologies are developed through scientific research. Preventive health measures and public health initiatives are crucial for maintaining community health." },
  { text: "Space exploration inspires innovation and scientific discovery. Satellites orbit the Earth, providing data for communication and environmental monitoring. Missions to other planets seek to uncover the mysteries of the cosmos and the potential for extraterrestrial life." },
  { text: "Literature offers a vast array of stories and perspectives. Books transport readers to different worlds and times, fostering imagination and empathy. From classic novels to contemporary works, literature enriches our lives and broadens our understanding of humanity." },
  { text: "Renewable energy sources are essential for a sustainable future. Solar, wind, and hydroelectric power provide clean alternatives to fossil fuels. These technologies help reduce greenhouse gas emissions and mitigate the effects of climate change." },
  { text: "The ocean is home to diverse ecosystems and marine life. Scientists explore underwater habitats to understand their complexity and significance. Discoveries of new species and geological features contribute to our knowledge of the marine environment." },
  { text: "Music has the ability to evoke a wide range of emotions and connect people. From classical symphonies to modern pop songs, music is a universal language. It plays a significant role in cultural expression and personal enjoyment." },
  { text: "Digital technology has revolutionized communication and information access. The internet connects people globally, enabling the exchange of ideas and knowledge. Social media, online education, and e-commerce have become integral parts of modern society." },
  { text: "Genetic research is advancing our understanding of human biology and disease. By analyzing DNA, scientists can identify genetic markers and develop targeted therapies. This field holds promise for personalized medicine and improved healthcare outcomes." },
  { text: "Artistic expression enriches our lives and reflects cultural diversity. Artists use various mediums to convey their ideas and emotions. Art exhibitions and installations provide opportunities for public engagement and appreciation." },
  { text: "Environmental conservation is vital for protecting natural resources and biodiversity. Efforts to reduce pollution and preserve ecosystems are essential. Sustainable practices in agriculture, industry, and daily life contribute to a healthier planet." },
  { text: "The field of robotics is making significant strides in technology and application. Robots assist in tasks ranging from manufacturing to healthcare. Their precision and efficiency make them valuable assets in many industries." },
  { text: "Astronomy continues to uncover the wonders of the universe. Telescopes and space probes explore distant galaxies and cosmic phenomena. The study of celestial bodies helps us understand the origins and evolution of the cosmos." },
  { text: "The culinary arts celebrate the diversity of food and cooking traditions. Chefs and home cooks experiment with flavors and techniques to create memorable meals. Food is a reflection of cultural heritage and offers a taste of different parts of the world." },
  { text: "Advancements in medical science are improving healthcare and patient outcomes. Researchers develop new treatments and technologies through scientific research. Preventive medicine and public health initiatives play a crucial role in maintaining population health." },
  { text: "Space exploration has led to numerous technological innovations. Satellites provide data for communication, navigation, and environmental monitoring. Missions to other planets seek to uncover the mysteries of the cosmos and the potential for extraterrestrial life." },
];

export const trashText = [
  ...texts,
  { text: "Purple moonlight dances beyond the whispering gnome flutes." },
  { text: "Bubbles of laughter climb the spider's silky web of dreams." },
  { text: "Stars sing lullabies to the wandering clouds of mystery." },
  { text: "Candy-coated raindrops paint the sky with whispers." },
  { text: "Marshmallow fields stretch towards the cotton candy mountains." },
  { text: "Dreams of dragons whisper through the twilight breeze." },
  { text: "Sunflowers whisper secrets to the meandering rivers." },
  { text: "Galaxies pirouette in the ballroom of cosmic wonder." },
  { text: "Rainbow unicorns dance under the silver moonlight." },
  { text: "Wind chimes play melodies of forgotten fairy tales." },
  { text: "Crystal caverns echo the songs of ancient mermaids." },
  { text: "Ethereal butterflies flutter in the garden of whispers." },
  { text: "Stars swim in the ocean of infinite possibilities." },
  { text: "Moonlit owls hoot the symphony of the enchanted forest." },
  { text: "Cotton clouds float on the breeze of whimsical dreams." },
  { text: "Mystic rivers flow through the valleys of twilight." },
  { text: "Velvet shadows dance in the embrace of twilight." },
  { text: "Dreamcatchers weave the stories of the ancient winds." },
  { text: "Gemstone dragons slumber under the moon's soft glow." },
  { text: "Whispers of the past echo in the valley of dreams." },
  { text: "Crystal castles float on clouds of wonder." },
  { text: "Moonbeams kiss the petals of the midnight roses." },
  { text: "Fairy dust sprinkles the twilight with magic." },
  { text: "Dreaming wolves howl at the crescent moon." },
  { text: "Celestial whales swim through the starlit sky." },
  { text: "Whispering winds tell tales of forgotten lands." },
  { text: "Rainbow foxes dart through fields of starlight." },
  { text: "Butterfly whispers float on the evening breeze." },
  { text: "Crystal snowflakes dance in the moonlit forest." },
  { text: "Unicorns gallop across the horizon of dreams." },
  { text: "Galactic rainbows bridge the realms of wonder." },
  { text: "Whispers of eternity echo in the starry night." },
  { text: "Mystic foxes play in the fields of time." },
  { text: "Starlit fairies dance in the moonbeam's glow." },
  { text: "Crystalline dreams shimmer in the twilight." },
  { text: "Glimmers of hope twinkle in the celestial sea." },
  { text: "Luminous owls watch over the dreamscape." },
  { text: "Ethereal foxes frolic in the meadow of stars." },
  { text: "Galactic winds weave tales of wonder." },
  { text: "Midnight owls whisper secrets to the moon." },
  { text: "Starlit rivers flow through valleys of dreams." },
  { text: "Mystic dolphins leap in the sea of stars." },
  { text: "Celestial butterflies flit through cosmic gardens." },
  { text: "Whispers of stardust echo in the twilight." },
  { text: "Luminous dreams float on the midnight breeze." },
  { text: "Eternal foxes play in the cosmic fields." },
  { text: "Galactic whispers drift through the void." },
  { text: "Mystic cats prowl in the moonlit forest." },
  { text: "Starlit whispers dance in the evening air." },
  { text: "Celestial dragons soar through the twilight sky." },
  { text: "Ethereal waves crash on the shores of time." },
  { text: "Whispering stars tell tales of old." },
  { text: "Mystic horses gallop through fields of dreams." },
  { text: "Galactic melodies float through the void." },
  { text: "Luminous clouds drift in the night sky." },
  { text: "Eternal owls gaze at the stars." },
  { text: "Cosmic foxes chase the moonbeams." },
  { text: "Whispers of the past echo in the starlit night." },
  { text: "Galactic dreams shimmer in the twilight." },
  { text: "Mystic dragons sleep under the moon's light." },
  { text: "Celestial rivers flow through the dreamscape." },
  { text: "Starlit fairies sing in the moonlit forest." },
  { text: "Ethereal clouds float on the midnight breeze." },
  { text: "Whispering winds tell tales of wonder." },
  { text: "Mystic owls hoot in the moonlit valley." },
  { text: "Galactic foxes dance in the fields of dreams." },
  { text: "Eternal butterflies flit through cosmic meadows." },
  { text: "Celestial waves crash on the shores of time." },
  { text: "Whispers of the cosmos echo in the night." },
  { text: "Luminous dolphins leap in the sea of stars." },
  { text: "Mystic stars twinkle in the void." },
  { text: "Galactic rivers flow through the starlit night." },
  { text: "Celestial dreams shimmer in the twilight." },
  { text: "Ethereal foxes frolic in the moonlit forest." },
  { text: "Whispering owls hoot in the valley of dreams." },
  { text: "Luminous waves crash on cosmic shores." },
  { text: "Mystic butterflies flutter through the night." },
  { text: "Galactic horses gallop through fields of stars." },
  { text: "Celestial foxes dance under the moonlight." },
  { text: "Eternal stars shine in the midnight sky." },
  { text: "Whispering dragons sleep in the valley of dreams." },
  { text: "Luminous dolphins swim in the cosmic sea." },
  { text: "Mystic clouds drift through the starlit night." },
  { text: "Galactic fairies sing in the moonlit forest." },
  { text: "Celestial waves whisper on the shores of time." },
  { text: "Ethereal owls gaze at the cosmic wonders." },
  { text: "Whispering foxes play in the fields of dreams." },
  { text: "Luminous stars twinkle in the night sky." },
  { text: "Mystic rivers flow through the valley of dreams." },
  { text: "Galactic whispers drift through the void." },
  { text: "Celestial butterflies flutter in the moonlit garden." },
  { text: "Eternal dragons soar in the cosmic sky." },
  { text: "Whispering waves crash on the starlit shores." },
  { text: "Luminous dreams float in the midnight air." },
  { text: "Mystic fairies dance in the moonlit forest." },
  { text: "Galactic owls hoot in the valley of dreams." },
  { text: "Celestial stars shine in the cosmic night." },
];
